In [136]:

from google.colab import files

import pandas as pd
from google.colab import files
uploaded = files.upload()
weatherdata_munich = pd.read_csv('weatherdata.csv')
weatherdata_munich.head()

Saving weatherdata.csv to weatherdata (7).csv

  STATIONS_ID;MESS_DATUM;QN_3;  FX;  FM;QN_4; RSK;RSKF; SDK;SHK_TAG;  NM; VPM;  PM; TMK; UPM; TXK; TNK; TGK;eor
0         3379;19540601;-999;-999;-999;    1;   0...
1         3379;19540602;-999;-999;-999;    1;   0...
2         3379;19540603;-999;-999;-999;    1;   0...
3         3379;19540604;-999;-999;-999;    1;   1...
4         3379;19540605;-999;-999;-999;    1;   6...

In [137]:
weatherdata_munich.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 1 columns):
 #   Column                                                                                                         Non-Null Count  Dtype
---  ------                                                                                                         --------------  -----
 0   STATIONS_ID;MESS_DATUM;QN_3;  FX;  FM;QN_4; RSK;RSKF; SDK;SHK_TAG;  NM; VPM;  PM; TMK; UPM; TXK; TNK; TGK;eor  25051 non-null  object
dtypes: object(1)
memory usage: 195.8+ KB

In [138]:
weatherdata_munich = pd.read_csv('weatherdata.csv',delimiter=';')
weatherdata_munich.head()

,STATIONS_ID,MESS_DATUM,QN_3,FX,FM,QN_4,RSK,RSKF,SDK,SHK_TAG,NM,VPM,PM,TMK,UPM,TXK,TNK,TGK,eor
0,3379,19540601,-999,-999.0,-999.0,1,0.0,1,-999.0,0,-999.0,-999.0,-999.0,14.0,-999.0,17.6,10.4,-999.0,eor
1,3379,19540602,-999,-999.0,-999.0,1,0.5,1,-999.0,0,-999.0,-999.0,-999.0,13.2,-999.0,19.7,9.7,-999.0,eor
2,3379,19540603,-999,-999.0,-999.0,1,0.0,1,-999.0,0,-999.0,-999.0,-999.0,16.6,-999.0,21.9,8.2,-999.0,eor
3,3379,19540604,-999,-999.0,-999.0,1,1.2,1,-999.0,0,-999.0,-999.0,-999.0,15.2,-999.0,17.3,11.8,-999.0,eor
4,3379,19540605,-999,-999.0,-999.0,1,6.0,1,-999.0,0,-999.0,-999.0,-999.0,15.2,-999.0,17.7,13.7,-999.0,eor

In [139]:
weatherdata_munich.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STATIONS_ID  25051 non-null  int64
 1   MESS_DATUM   25051 non-null  int64
 2   QN_3         25051 non-null  int64
 3     FX         25051 non-null  float64
 4     FM         25051 non-null  float64
 5   QN_4         25051 non-null  int64
 6    RSK         25051 non-null  float64
 7   RSKF         25051 non-null  int64
 8    SDK         25051 non-null  float64
 9   SHK_TAG      25051 non-null  int64
 10    NM         25051 non-null  float64
 11   VPM         25051 non-null  float64
 12    PM         25051 non-null  float64
 13   TMK         25051 non-null  float64
 14   UPM         25051 non-null  float64
 15   TXK         25051 non-null  float64
 16   TNK         25051 non-null  float64
 17   TGK         25051 non-null  float64
 18  eor          25051 non-null  object
dtypes: float64(12), int64(6), object(1)
memory usage: 3.6+ MB

In [140]:
weatherdata_munich.columns = weatherdata_munich.columns.str.strip().str.lower()
weatherdata_munich.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  int64
 2   qn_3         25051 non-null  int64
 3   fx           25051 non-null  float64
 4   fm           25051 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          25051 non-null  float64
 9   shk_tag      25051 non-null  int64
 10  nm           25051 non-null  float64
 11  vpm          25051 non-null  float64
 12  pm           25051 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          25051 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          25051 non-null  float64
 18  eor          25051 non-null  object
dtypes: float64(12), int64(6), object(1)
memory usage: 3.6+ MB

In [141]:
unique_counts_columns = weatherdata_munich.nunique()
print(unique_counts_columns)

stations_id        1
mess_datum     25051
qn_3               3
fx               279
fm               102
qn_4               4
rsk              442
rskf               6
sdk              488
shk_tag           51
nm                82
vpm              200
pm               939
tmk              444
upm              504
txk              484
tnk              413
tgk              395
eor                1
dtype: int64

In [154]:
import numpy as np
import numpy as np


weatherdata_munich['mess_datum'] = pd.to_datetime(weatherdata_munich['mess_datum'], format='%Y%m%d', errors='coerce')
weatherdata_munich.info()
weatherdata_munich.head()
print(weatherdata_munich.duplicated())
weatherdata_munich.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_3         13879 non-null  float64
 3   fx           13793 non-null  float64
 4   fm           13809 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          24746 non-null  float64
 9   shk_tag      23484 non-null  float64
 10  nm           13860 non-null  float64
 11  vpm          13874 non-null  float64
 12  pm           13874 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          13874 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          13863 non-null  float64
 18  eor          25051 non-null  object
dtypes: datetime64[ns](1), float64(14), int64(3), object(1)
memory usage: 3.6+ MB
0        False
1        False
2        False
3        False
4        False
         ...
25046    False
25047    False
25048    False
25049    False
25050    False
Length: 25051, dtype: bool

,stations_id,mess_datum,qn_3,fx,fm,qn_4,rsk,rskf,sdk,shk_tag,nm,vpm,pm,tmk,upm,txk,tnk,tgk
count,25051.0,25051,13879.000000,13793.000000,13809.000000,25051.000000,25051.000000,25051.000000,24746.000000,23484.000000,13860.000000,13874.000000,13874.000000,25051.000000,13874.000000,25051.000000,25051.000000,13863.000000
mean,3379.0,1988-09-15 00:00:00,9.845666,9.402596,2.528329,5.661530,2.627951,2.686679,4.851322,1.013328,5.246912,9.511583,955.082710,9.612083,73.308082,13.828729,5.658369,4.923494
min,3379.0,1954-06-01 00:00:00,3.000000,0.900000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.200000,912.600000,-20.000000,20.000000,-17.900000,-25.400000,-23.500000
25%,3379.0,1971-07-24 12:00:00,10.000000,6.300000,1.700000,1.000000,0.000000,0.000000,0.500000,0.000000,3.700000,6.200000,950.800000,3.400000,64.000000,6.700000,0.500000,-0.200000
50%,3379.0,1988-09-15 00:00:00,10.000000,8.400000,2.300000,9.000000,0.000000,1.000000,4.000000,0.000000,5.800000,8.800000,955.600000,9.900000,74.000000,14.200000,5.900000,5.100000
75%,3379.0,2005-11-07 12:00:00,10.000000,11.500000,3.000000,10.000000,2.600000,6.000000,8.400000,0.000000,7.300000,12.600000,960.000000,15.800000,84.000000,20.900000,11.400000,10.700000
max,3379.0,2022-12-31 00:00:00,10.000000,38.600000,11.000000,10.000000,101.600000,8.000000,15.717000,55.000000,8.000000,21.500000,979.600000,30.400000,100.000000,37.500000,22.600000,21.400000
std,0.0,NaN,1.027908,4.293801,1.273273,4.318503,5.911350,2.880991,4.363261,3.663570,2.367752,4.060903,7.511599,7.908055,13.350102,9.013736,7.036732,7.070412

In [143]:
weatherdata_munich_formated = weatherdata_munich.drop(columns=['eor'])

# Check the structure of the new DataFrame
weatherdata_munich_formated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_3         13879 non-null  float64
 3   fx           13793 non-null  float64
 4   fm           13809 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          24746 non-null  float64
 9   shk_tag      23484 non-null  float64
 10  nm           13860 non-null  float64
 11  vpm          13874 non-null  float64
 12  pm           13874 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          13874 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          13863 non-null  float64
dtypes: datetime64[ns](1), float64(14), int64(3)
memory usage: 3.4 MB

In [181]:
weatherdata_munich_formated['Year'] = weatherdata_munich_formated['mess_datum'].dt.year
weatherdata_munich_formated['Month'] = weatherdata_munich_formated['mess_datum'].dt.month
weatherdata_munich_formated['Week'] = weatherdata_munich_formated['mess_datum'].dt.isocalendar().week
weatherdata_munich_formated.head()
weatherdata_munich_formated.describe()

,stations_id,mess_datum,qn_3,fx,fm,qn_4,rsk,rskf,sdk,shk_tag,...,vpm,pm,tmk,upm,txk,tnk,tgk,Year,Month,Week
count,25051.0,25051,13879.000000,13793.000000,13809.000000,25051.000000,25051.000000,25051.000000,24746.000000,23484.000000,...,13874.000000,13874.000000,25051.000000,13874.000000,25051.000000,25051.000000,13863.000000,25051.000000,25051.000000,25051.0
mean,3379.0,1988-09-15 00:00:00,9.845666,9.402596,2.528329,5.661530,2.627951,2.686679,4.851322,1.013328,...,9.511583,955.082710,9.612083,73.308082,13.828729,5.658369,4.923494,1988.204942,6.544130,26.678975
min,3379.0,1954-06-01 00:00:00,3.000000,0.900000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.200000,912.600000,-20.000000,20.000000,-17.900000,-25.400000,-23.500000,1954.000000,1.000000,1.0
25%,3379.0,1971-07-24 12:00:00,10.000000,6.300000,1.700000,1.000000,0.000000,0.000000,0.500000,0.000000,...,6.200000,950.800000,3.400000,64.000000,6.700000,0.500000,-0.200000,1971.000000,4.000000,14.0
50%,3379.0,1988-09-15 00:00:00,10.000000,8.400000,2.300000,9.000000,0.000000,1.000000,4.000000,0.000000,...,8.800000,955.600000,9.900000,74.000000,14.200000,5.900000,5.100000,1988.000000,7.000000,27.0
75%,3379.0,2005-11-07 12:00:00,10.000000,11.500000,3.000000,10.000000,2.600000,6.000000,8.400000,0.000000,...,12.600000,960.000000,15.800000,84.000000,20.900000,11.400000,10.700000,2005.000000,10.000000,40.0
max,3379.0,2022-12-31 00:00:00,10.000000,38.600000,11.000000,10.000000,101.600000,8.000000,15.717000,55.000000,...,21.500000,979.600000,30.400000,100.000000,37.500000,22.600000,21.400000,2022.000000,12.000000,53.0
std,0.0,NaN,1.027908,4.293801,1.273273,4.318503,5.911350,2.880991,4.363261,3.663570,...,4.060903,7.511599,7.908055,13.350102,9.013736,7.036732,7.070412,19.800371,3.446552,15.050399

In [198]:
 print(weatherdata_munich_formated[['Year', 'Month', 'Week']].head())
print(weatherdata_munich_formated.dtypes)

   Year  Month  Week
0  1954      6    22
1  1954      6    22
2  1954      6    22
3  1954      6    22
4  1954      6    22
stations_id             int64
mess_datum     datetime64[ns]
qn_3                  float64
fx                    float64
fm                    float64
qn_4                    int64
rsk                   float64
rskf                    int64
sdk                   float64
shk_tag               float64
nm                    float64
vpm                   float64
pm                    float64
tmk                   float64
upm                   float64
txk                   float64
tnk                   float64
tgk                   float64
Year                    int32
Month                   int32
Week                   UInt32
dtype: object

In [199]:
weatherdata_munich_formated_filled = weatherdata_munich_formated.groupby(['Year', 'Week']).apply(
    lambda group: group.fillna(group.mean(numeric_only=True))
)
weatherdata_munich_formated_filled.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 25051 entries, (1954, 22, 0) to (2022, 52, 25050)
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_3         13879 non-null  float64
 3   fx           13833 non-null  float64
 4   fm           13833 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          24753 non-null  float64
 9   shk_tag      23554 non-null  float64
 10  nm           13879 non-null  float64
 11  vpm          13879 non-null  float64
 12  pm           13879 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          13879 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          13879 non-null  float64
 18  Year         25051 non-null  int32
 19  Month        25051 non-null  int32
 20  Week         25051 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(14), int32(2), int64(3)
memory usage: 4.5 MB

<ipython-input-199-4e78af4d3c9b>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weatherdata_munich_formated_filled = weatherdata_munich_formated.groupby(['Year', 'Week']).apply(

In [200]:
weatherdata_munich_formated_filled = weatherdata_munich_formated.replace(-999, np.nan)


weatherdata_munich_formated_filled = weatherdata_munich_formated_filled.groupby(['Year', 'Week']).apply(
    lambda group: group.fillna(group.mean(numeric_only=True))
)


weatherdata_munich_formated_filled.reset_index(drop=True, inplace=True)


weatherdata_munich_formated_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_3         13879 non-null  float64
 3   fx           13833 non-null  float64
 4   fm           13833 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          24753 non-null  float64
 9   shk_tag      23554 non-null  float64
 10  nm           13879 non-null  float64
 11  vpm          13879 non-null  float64
 12  pm           13879 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          13879 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          13879 non-null  float64
 18  Year         25051 non-null  int32
 19  Month        25051 non-null  int32
 20  Week         25051 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(14), int32(2), int64(3)
memory usage: 3.8 MB

<ipython-input-200-d9d39bd26878>:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weatherdata_munich_formated_filled = weatherdata_munich_formated_filled.groupby(['Year', 'Week']).apply(

In [201]:
weatherdata_munich_formated_filled_reset = weatherdata_munich_formated_filled.reset_index(drop=True)
weatherdata_munich_formated_filled_reset.info()
weatherdata_munich_formated_filled_reset.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_3         13879 non-null  float64
 3   fx           13833 non-null  float64
 4   fm           13833 non-null  float64
 5   qn_4         25051 non-null  int64
 6   rsk          25051 non-null  float64
 7   rskf         25051 non-null  int64
 8   sdk          24753 non-null  float64
 9   shk_tag      23554 non-null  float64
 10  nm           13879 non-null  float64
 11  vpm          13879 non-null  float64
 12  pm           13879 non-null  float64
 13  tmk          25051 non-null  float64
 14  upm          13879 non-null  float64
 15  txk          25051 non-null  float64
 16  tnk          25051 non-null  float64
 17  tgk          13879 non-null  float64
 18  Year         25051 non-null  int32
 19  Month        25051 non-null  int32
 20  Week         25051 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(14), int32(2), int64(3)
memory usage: 3.8 MB

,stations_id,mess_datum,qn_3,fx,fm,qn_4,rsk,rskf,sdk,shk_tag,...,vpm,pm,tmk,upm,txk,tnk,tgk,Year,Month,Week
count,25051.0,25051,13879.000000,13833.000000,13833.00000,25051.000000,25051.000000,25051.000000,24753.000000,23554.000000,...,13879.000000,13879.000000,25051.000000,13879.000000,25051.000000,25051.000000,13879.000000,25051.000000,25051.000000,25051.0
mean,3379.0,1988-09-15 00:00:00,9.845666,9.402458,2.52768,5.661530,2.627951,2.686679,4.851592,1.012148,...,9.514135,955.083938,9.612083,73.308521,13.828729,5.658369,4.924764,1988.204942,6.544130,26.678975
min,3379.0,1954-06-01 00:00:00,3.000000,0.900000,0.10000,1.000000,0.000000,0.000000,0.000000,0.000000,...,1.200000,912.600000,-20.000000,20.000000,-17.900000,-25.400000,-23.500000,1954.000000,1.000000,1.0
25%,3379.0,1971-07-24 12:00:00,10.000000,6.300000,1.70000,1.000000,0.000000,0.000000,0.500000,0.000000,...,6.200000,950.800000,3.400000,64.000000,6.700000,0.500000,-0.200000,1971.000000,4.000000,14.0
50%,3379.0,1988-09-15 00:00:00,10.000000,8.400000,2.30000,9.000000,0.000000,1.000000,4.000000,0.000000,...,8.800000,955.600000,9.900000,74.000000,14.200000,5.900000,5.100000,1988.000000,7.000000,27.0
75%,3379.0,2005-11-07 12:00:00,10.000000,11.500000,3.00000,10.000000,2.600000,6.000000,8.400000,0.000000,...,12.600000,960.000000,15.800000,84.000000,20.900000,11.400000,10.700000,2005.000000,10.000000,40.0
max,3379.0,2022-12-31 00:00:00,10.000000,38.600000,11.00000,10.000000,101.600000,8.000000,15.717000,55.000000,...,21.500000,979.600000,30.400000,100.000000,37.500000,22.600000,21.400000,2022.000000,12.000000,53.0
std,0.0,NaN,1.027908,4.289225,1.27239,4.318503,5.911350,2.880991,4.363044,3.659469,...,4.062406,7.510589,7.908055,13.347790,9.013736,7.036732,7.068407,19.800371,3.446552,15.050399

In [202]:
completely_mising_months = weatherdata_munich_formated_filled_reset.groupby(['Year', 'Month']).apply(
    lambda group: group.isnull().all()
)
print(completely_mising_months)

            stations_id  mess_datum   qn_3     fx     fm   qn_4    rsk   rskf  \
Year Month
1954 6            False       False   True   True   True  False  False  False
     7            False       False   True   True   True  False  False  False
     8            False       False   True   True   True  False  False  False
     9            False       False   True   True   True  False  False  False
     10           False       False   True   True   True  False  False  False
...                 ...         ...    ...    ...    ...    ...    ...    ...
2022 8            False       False  False  False  False  False  False  False
     9            False       False  False  False  False  False  False  False
     10           False       False  False  False  False  False  False  False
     11           False       False  False  False  False  False  False  False
     12           False       False  False  False  False  False  False  False

              sdk  shk_tag  ...    vpm     pm    tmk    upm    txk    tnk  \
Year Month                  ...
1954 6       True    False  ...   True   True  False   True  False  False
     7       True    False  ...   True   True  False   True  False  False
     8       True    False  ...   True   True  False   True  False  False
     9       True    False  ...   True   True  False   True  False  False
     10      True    False  ...   True   True  False   True  False  False
...           ...      ...  ...    ...    ...    ...    ...    ...    ...
2022 8      False    False  ...  False  False  False  False  False  False
     9      False    False  ...  False  False  False  False  False  False
     10     False    False  ...  False  False  False  False  False  False
     11     False    False  ...  False  False  False  False  False  False
     12     False    False  ...  False  False  False  False  False  False

              tgk   Year  Month   Week
Year Month
1954 6       True  False  False  False
     7       True  False  False  False
     8       True  False  False  False
     9       True  False  False  False
     10      True  False  False  False
...           ...    ...    ...    ...
2022 8      False  False  False  False
     9      False  False  False  False
     10     False  False  False  False
     11     False  False  False  False
     12     False  False  False  False

[823 rows x 21 columns]

<ipython-input-202-21b8f8aa342f>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  completely_mising_months = weatherdata_munich_formated_filled_reset.groupby(['Year', 'Month']).apply(

In [203]:
years_mising_data = weatherdata_munich_formated_filled_reset.groupby(['Year']).apply(
    lambda group: group.isnull().all()
)
missing_years = years_mising_data[years_mising_data.all(axis=1)]
print(missing_years)
missing_years.info()

Empty DataFrame
Columns: [stations_id, mess_datum, qn_3, fx, fm, qn_4, rsk, rskf, sdk, shk_tag, nm, vpm, pm, tmk, upm, txk, tnk, tgk, Year, Month, Week]
Index: []

[0 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  0 non-null      bool
 1   mess_datum   0 non-null      bool
 2   qn_3         0 non-null      bool
 3   fx           0 non-null      bool
 4   fm           0 non-null      bool
 5   qn_4         0 non-null      bool
 6   rsk          0 non-null      bool
 7   rskf         0 non-null      bool
 8   sdk          0 non-null      bool
 9   shk_tag      0 non-null      bool
 10  nm           0 non-null      bool
 11  vpm          0 non-null      bool
 12  pm           0 non-null      bool
 13  tmk          0 non-null      bool
 14  upm          0 non-null      bool
 15  txk          0 non-null      bool
 16  tnk          0 non-null      bool
 17  tgk          0 non-null      bool
 18  Year         0 non-null      bool
 19  Month        0 non-null      bool
 20  Week         0 non-null      bool
dtypes: bool(21)
memory usage: 0.0 bytes

<ipython-input-203-1ffb3da8a03b>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  years_mising_data = weatherdata_munich_formated_filled_reset.groupby(['Year']).apply(

In [204]:
weatherdata_munich_formated_filled.drop(columns=['fx','fm','qn_3','vpm', 'pm','tgk','upm','sdk','nm'], inplace=True)
weatherdata_munich_formated_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_4         25051 non-null  int64
 3   rsk          25051 non-null  float64
 4   rskf         25051 non-null  int64
 5   shk_tag      23554 non-null  float64
 6   tmk          25051 non-null  float64
 7   txk          25051 non-null  float64
 8   tnk          25051 non-null  float64
 9   Year         25051 non-null  int32
 10  Month        25051 non-null  int32
 11  Week         25051 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(5), int32(2), int64(3)
memory usage: 2.0 MB

In [210]:
missing_shk_tag = weatherdata_munich_formated_filled[weatherdata_munich_formated_filled['shk_tag'].isnull()]
print(missing_shk_tag)
shk_tag_mode = weatherdata_munich_formated_filled['shk_tag'].mode()[0]
print(shk_tag_mode)
weatherdata_munich_formated_filled['shk_tag'].fillna(shk_tag_mode, inplace=True)
print(weatherdata_munich_formated_filled.isnull().sum())

       stations_id mess_datum  qn_4  rsk  rskf  shk_tag   tmk   txk   tnk  \
20787         3379 2011-05-02     9  6.1     4      NaN  12.6  19.7   7.0
20788         3379 2011-05-03     9  1.4     4      NaN   7.4  11.4   3.5
20789         3379 2011-05-04     9  0.0     0      NaN   6.6  13.2   0.6
20790         3379 2011-05-05     9  0.0     0      NaN   9.7  16.7   1.0
20791         3379 2011-05-06     9  0.0     0      NaN  13.3  22.5   3.5
...            ...        ...   ...  ...   ...      ...   ...   ...   ...
24235         3379 2020-10-07     9  3.9     6      NaN  10.1  13.4   8.5
24236         3379 2020-10-08     9  0.0     0      NaN  12.7  17.7   8.7
24237         3379 2020-10-09     9  0.0     6      NaN  14.4  19.0  10.1
24238         3379 2020-10-10     9  8.3     6      NaN   9.6  13.0   7.1
24239         3379 2020-10-11     9  0.4     6      NaN   7.3   9.9   5.6

       Year  Month  Week
20787  2011      5    18
20788  2011      5    18
20789  2011      5    18
20790  2011      5    18
20791  2011      5    18
...     ...    ...   ...
24235  2020     10    41
24236  2020     10    41
24237  2020     10    41
24238  2020     10    41
24239  2020     10    41

[1497 rows x 12 columns]
0.0
stations_id    0
mess_datum     0
qn_4           0
rsk            0
rskf           0
shk_tag        0
tmk            0
txk            0
tnk            0
Year           0
Month          0
Week           0
dtype: int64

In [211]:
weatherdata_munich_formated_filled.to_csv('weatherdata_munich_formated_filled.csv', index=False)
weatherdata_munich_formated_filled.info()
weatherdata_munich_formated_filled.describe()
weatherdata_munich_formated_filled.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25051 entries, 0 to 25050
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stations_id  25051 non-null  int64
 1   mess_datum   25051 non-null  datetime64[ns]
 2   qn_4         25051 non-null  int64
 3   rsk          25051 non-null  float64
 4   rskf         25051 non-null  int64
 5   shk_tag      25051 non-null  float64
 6   tmk          25051 non-null  float64
 7   txk          25051 non-null  float64
 8   tnk          25051 non-null  float64
 9   Year         25051 non-null  int32
 10  Month        25051 non-null  int32
 11  Week         25051 non-null  UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(5), int32(2), int64(3)
memory usage: 2.0 MB

,stations_id,mess_datum,qn_4,rsk,rskf,shk_tag,tmk,txk,tnk,Year,Month,Week
0,3379,1954-06-01,1,0.0,1,0.0,14.0,17.6,10.4,1954,6,22
1,3379,1954-06-02,1,0.5,1,0.0,13.2,19.7,9.7,1954,6,22
2,3379,1954-06-03,1,0.0,1,0.0,16.6,21.9,8.2,1954,6,22
3,3379,1954-06-04,1,1.2,1,0.0,15.2,17.3,11.8,1954,6,22
4,3379,1954-06-05,1,6.0,1,0.0,15.2,17.7,13.7,1954,6,22